@startuml
!include <C4/C4_Context>

Person(user, "Пользователь", "Управляет отоплением, получает телеметрию")
Person(specialist, "Специалист по установке", "Регистрирует устройства вручную")

System(warmhouse, "Система Тёплый дом", "Монолит на Go. Управление системами отопления.")
System_Ext(sensor, "Система отопления", "Получение данных о температуре, управление температурой")

Rel(user, warmhouse, "Управляет отоплением, просматривает температуру")
Rel(specialist, warmhouse, "Регистрирует устройства")

Rel(warmhouse, sensor, "Получает температуру", "HTTP")

@enduml
