@startuml
!include <C4/C4_Context>

Person(user, "Пользователь", "Самостоятельно подключает и управляет устройствами, получает телеметрию")

System(ecosystem, "Экосистема WarmHouse", "SaaS-платформа, пригодная для подключения различных систем. Адаптируется под протокол поставщика")

System_Ext(warmhouse, "Старая монолитная система управления домами", "Реализует собственный протокол управления.")
System_Ext(other_providers, "Внешние системы", "Освещение, наблюдение, свет и т.д.")

Rel(user, ecosystem, "Взаимодействие через веб-интерфейс")
Rel(ecosystem, warmhouse, "Управление и сбор телеметрии", "HTTP")
Rel(ecosystem, other_providers, "Управление и сбор телеметрии", "API/Webhook/AMQP/RPC/SOAP")
@enduml